name: RPG
version: 0.2
author: Tempoo50
main: de.tempoo50.rpg.main.Rpg

commands:
   cow:
      description:
   pig:
      description:
   witch:
      description:
   zombie:
      description:
   skelett:
      description:
   spider:
      description:
   giant:
      description:
   villager:
      description:
   evoker:
      description:
   slime:
      description:
   vindi:
      description:
   creeper:
      description:
   blaze:
      description:
   wither:
      description:
   illi:
      description:
   vex:
      description:
   stray:
      description:
   setspawn:
      description:
   setrespawn:
      description:
   spawn:
      description:
   home:
      description:
   sethome:
      description:
   delhome:
      description:
   blacklist:
      description:
   tp:
      description:
   msg:
      description:
   r:
      description:
   cc:
      description:
   fly:
      description:
   day:
      description:
   night:
      description:
   runfruf:
      description:
   discord:
      description:
   forum:
      description:
   ts:
      description:
   web:
      description:
   shop:
      description:
   vote:
      description:
   yt:
      description:
   insta:
      description:
   twitter:
      description: